from __future__ import annotations

from enum import Enum


class WorkflowStatus(str, Enum):
    NEW = "NEW"
    RUNNING = "RUNNING"
    WAIT_USER = "WAIT_USER"
    COMPLETED = "COMPLETED"
    PARTIAL_SUCCESS = "PARTIAL_SUCCESS"
    FAILED = "FAILED"


class IntentStatus(str, Enum):
    PENDING = "PENDING"
    READY = "READY"
    RUNNING = "RUNNING"
    WAIT_USER = "WAIT_USER"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    BLOCKED_BY_UPSTREAM = "BLOCKED_BY_UPSTREAM"


class IntentPhase(str, Enum):
    CONTEXT_BUILDING = "CONTEXT_BUILDING"
    SCHEMALINK = "SCHEMALINK"
    PLAN_RA = "PLAN_RA"
    RENDER_SQL = "RENDER_SQL"
    VALIDATE_SQL = "VALIDATE_SQL"
    EXECUTE_SQL = "EXECUTE_SQL"
    INTERPRET_RESULT = "INTERPRET_RESULT"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    WAIT_USER = "WAIT_USER"


class ModuleStatus(str, Enum):
    SUCCESS = "SUCCESS"
    WAIT_USER = "WAIT_USER"
    RETRYABLE_ERROR = "RETRYABLE_ERROR"
    FATAL_ERROR = "FATAL_ERROR"
    UPSTREAM_ERROR = "UPSTREAM_ERROR"


class StageName(str, Enum):
    INTENT_DECOMPOSE = "INTENT_DECOMPOSE"
    INTENT_TOPOLOGY = "INTENT_TOPOLOGY"
    CONTEXT_BUILD = "CONTEXT_BUILD"
    SCHEMALINK = "SCHEMALINK"
    PLAN_RA = "PLAN_RA"
    RENDER_SQL = "RENDER_SQL"
    VALIDATE_SQL = "VALIDATE_SQL"
    EXECUTE_SQL = "EXECUTE_SQL"
    INTERPRET_RESULT = "INTERPRET_RESULT"
    SYNTHESIZE_RESULT = "SYNTHESIZE_RESULT"


class RepairAction(str, Enum):
    RETRY_CURRENT = "RETRY_CURRENT"
    REBUILD_SCHEMA = "REBUILD_SCHEMA"
    ENRICH_SCHEMA = "ENRICH_SCHEMA"
    REPLAN_RA = "REPLAN_RA"
    RERENDER_SQL = "RERENDER_SQL"
    REVALIDATE_SQL = "REVALIDATE_SQL"
    REEXECUTE_SQL = "REEXECUTE_SQL"
    REINTERPRET_RESULT = "REINTERPRET_RESULT"
    ASK_USER = "ASK_USER"
    STOP = "STOP"


class AskTicketStatus(str, Enum):
    OPEN = "OPEN"
    ANSWERED = "ANSWERED"
    CLOSED = "CLOSED"

